version = 0.1
[default.deploy.parameters]
stack_name = "sam-clock-lambda"
resolve_s3 = true
s3_prefix = "sam-clock-lambda"
region = "eu-west-1"
profile = "deployer"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
