name: Test
permissions: write-all
on: # rebuild any PRs and pushes
  pull_request:
  push:

jobs:
  test:
    name: Test, rollback if tests fail.
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Test the code
        run: |
          pipx install poetry && \
          poetry install && \
          poetry run pytest && \
          poetry run ruff check

      - name: Rollback if tests fails
        if: failure()
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git reset --hard latest
          git push --force
